Fix battery drain crash for GoToPlace
open-rmf/rmf_task pull request #94
Opened 2023-07-10 09:49 UTC by Yadunund

Addresses https://github.com/open-rmf/rmf/issues/359

2023-07-11 02:41 UTC, mxgrey requested changes
Thanks for jumping on this problem.

I think for both cases we should do
```
const auto new_battery_soc = finish.battery_soc().value() - travel->change_in_charge();
if (new_battery_soc < 0.0)
  return std::nullopt;

finish.battery_soc(new_battery_soc);
```
instead of doing `finish.battery_soc(std::max(0.0, ...))`.

In the PR as it currently stands, there's a very narrow edge case where the user might have specified a `battery_threshold <= 0.0`, in which case a negative final battery charge would get disguised as a charge of 0.0 which is technically within the threshold, so the task would be performed even though it should be discarded.

Admittedly if the user is specifying a battery threshold of <= 0.0 then they're probably doing something very wrong already, but we should avoid making that bad situation even worse by allowing tasks to be performed when they won't even be able to finish.

2023-07-11 04:24 UTC, Yadunund commented on rmf_task_sequence/src/rmf_task_sequence/events/WaitFor.cpp
> +  if (state.battery_soc().value() <= constraints.threshold_soc())
Corrected this bug too.

2023-07-11 04:24 UTC, Yadunund commented
Thanks for the quick feedback and catching the edge case. I've updated the code as suggested. Also addressed this other issue in `WaitFor` event when the duration count is negative. Added some tests too.

2023-07-13 03:06 UTC, mxgrey approved these changes
Thanks for these fixes and the new unit tests!

2023-07-13 03:06 UTC, merged